apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-frontend
  template:
    metadata:
      labels:
        app: appointment-frontend
    spec:
      containers:
      - name: appointment-frontend
        image: <+artifact.image>:<+artifact.tag>
        ports:
        - containerPort: 80
